[proxy]
coverAll = false

[proxy.binding]
'docker.registry-proxy.localhost' = 'https://registry-1.docker.io'
'gcr.registry-proxy.localhost' = 'https://gcr.io'
'ghcr.registry-proxy.localhost' = 'https://ghcr.io'
'k8s.registry-proxy.localhost' = 'https://registry.k8s.io'
'quay.registry-proxy.localhost' = 'https://quay.io'

[server]
listen = ':80'
logLevel = 'INFO'

[server.tls]
enable = false
listen = ':443'
useLetsEncrypt = true
certPath = 'server.crt'
keyPath = 'server.key'
